services:
  - type: web
    name: agente-ia
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=8000"
    plan: free    
    
